github:
  user: ${gh_user}
  token: ${gh_token}
  secret: ${git_secret}
orgAllowlist: "github.com/97-naushad/*"
enableKubernetesBackend: true

# config: |
#   ---
#   version: 3
#   automerge: false
#   delete_source_branch_on_merge: true
#   parallel_plan: true
#   parallel_apply: true
#   projects:
#     - name: dev
#       dir: local-env/
#       autoplan:
#         when_modified: [ "*.tf", "../modules/**/*.tf", "*.tfvars" ]
#         enabled: true
#       terraform_version: v1.6.6
#       workflow: local-env

repoConfig: |
  ---
  repos:
  - id: github.com/97-naushad/project-app
    workflow: local-env
    allowed_workflows: [local-env]
    allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
    allow_custom_workflows: true
    autodiscover:
      mode: auto
  workflows:
    local-env:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]
