github:
  user: ${gh_user}
  token: ${gh_token}
  secret: ${git_secret}
orgAllowlist: "github.com/97-naushad/*"
enableKubernetesBackend: true

config: |
  ---
  version: 3
  automerge: false
  delete_source_branch_on_merge: true
  parallel_plan: true
  parallel_apply: true
  projects:
    - name: dev
      dir: ./local-env/
      workspace: default
      autoplan:
        when_modified: [ "*.tf", "../modules/**/*.tf", "*.tfvars" ]
        enabled: true
      terraform_version: v1.6.6
      workflow: dev_workflow
  workflows:
    dev_workflow:
      plan:
        steps:
          - run: echo "terraform init"
          - init
          - run: echo "terraform plan"
          - plan:
      apply:
        steps:
          - run: echo "terraform apply"
          - apply
