github:
  user: ${gh_user}
  token: ${gh_token}
  secret: ${git_secret}
orgAllowlist: "github.com/97-naushad/*"
enableKubernetesBackend: true

config: |
  ---
  version: 3
  automerge: false
  delete_source_branch_on_merge: true
  parallel_plan: true
  parallel_apply: true
  projects:
    - name: dev
      dir: local-env/
      autoplan:
        when_modified: [ "*.tf", "../modules/**/*.tf", "*.tfvars" ]
        enabled: true
      terraform_version: v1.6.6
      workflow: dev_workflow

repoConfig: |
  ---
  repos:
  - id: /.*/
    branch: /.*/
    allowed_overrides: [apply_requirements, workflow]
    workflow: dev_workflow
    allow_custom_workflows: true
  workflows:
    dev_workflow:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]
