github:
  user: ${gh_user}
  token: ${gh_token}
  secret: ${git_secret}
orgAllowlist: "github.com/97-naushad/*"
enableKubernetesBackend: true

config: |
  ---
  version: 3
  workflows:
    default:
      plan:
        steps:
        - run:
            command: terraform init -input=false
            output: hide
        - run: terraform plan -input=false -refresh -out $PLANFILE
      apply:
        steps:
        - run: terraform apply $PLANFILE

repoConfig: |
  ---
  repos:
  - id: /.*/    
    branch: /.*/
    workflow: default