github:
  user: ${gh_user}
  token: ${gh_token}
  secret: ${git_secret}
orgAllowlist: "github.com/97-naushad/*"
enableKubernetesBackend: true

config: |
  ---
  version: 3
  workflows:
    default:
      plan:
        steps:
          - init
          - plan
      apply:
        steps:
          - apply

repoConfig: |
  ---
  repos:
  - id: /.*/
    apply_requirements: []
    workflow: default
    allowed_overrides: []
    allow_custom_workflows: false
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]

